// src/app/layout.tsx

import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { Metadata } from "next";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Sabilul Huda Education Foundation",
  description: "Generated by Sabilul Huda Education Foundation",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={cn("font-sans", geist.variable)}>
      <body>
        <GoogleAnalytics />
        {children}
      </body>
    </html>
  );
}
