import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-bangla",
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sabilul Huda Education Foundation",
  description: "Generated by Sabilul Huda Education Foundation",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <div
      className={`
      ${geistSans.variable}
      ${geistMono.variable}
      ${hindSiliguri.variable}
      font-sans
    `}
    >
      {/* Global Background */}
      <div className="fixed inset-0 -z-10 overflow-hidden">
        <Image
          src="/background.png"
          alt="Islamic Background"
          fill
          priority
          sizes="100vw"
          className=" opacity-75"
        />

        <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/85 via-white/80 to-emerald-50/75" />
      </div>

      <NextIntlClientProvider locale={locale} messages={messages}>
        <Navbar />

        <main className="relative z-10">{children}</main>

        <Footer />
      </NextIntlClientProvider>
    </div>
  );
}
